version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_DB: $POSTGRES_DATABASE
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME} -d ${POSTGRES_DATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5

  telegram-bot:
    build: .
    env_file: .env
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.datasource.url": "jdbc:postgresql://postgres:${POSTGRES_DOCKER_PORT}/${POSTGRES_DATABASE}",
              "spring.datasource.username": "${POSTGRES_USERNAME}",
              "spring.datasource.password": "${POSTGRES_PASSWORD}",
              "spring.datasource.driver-class-name": "org.postgresql.Driver",
              "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.PostgreSQLDialect",
              "spring.liquibase.enabled": true,
              "spring.liquibase.change-log": "classpath:db/changelog/db.changelog-master.yaml"
            }'
      JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"

volumes:
  postgres_data: