spring.application.name=solscanbot

spring.thymeleaf.check-template-location=false
spring.jpa.open-in-view=false

telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
sol.scan.key=${SOL_SCAN_KEY}

spring.config.import=optional:file:.env[.properties]
